os: Visual Studio 2015

init:
  - ps: >-
      if ($env:appveyor_repo_tag -eq "true") {
        Update-AppveyorBuild -Version "$env:appveyor_repo_tag_name"
      } else {
        Update-AppveyorBuild -Version "dev-$($env:appveyor_repo_commit.substring(0,7))"
      }
  - git config --global core.autocrlf input

build:
  project: libwdi.sln
  parallel: true
  verbosity: detailed

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - curl -o libusb-win32-bin-1.2.6.0.zip -L http://files.akeo.ie/appveyor/libwdi/libusb-win32-bin-1.2.6.0.zip
  - curl -o libusbK-3.0.7.0-bin.7z -L http://files.akeo.ie/appveyor/libwdi/libusbK-3.0.7.0-bin.7z
  - 7z x libusb-win32-bin-1.2.6.0.zip
  - 7z x libusbK-3.0.7.0-bin.7z
  - dir

build_script:
  - msbuild "libwdi.sln" /m /p:BuildMacros="LIBUSB0_DIR=\"c:/projects/libwdi/libusb-win32-bin-1.2.6.0\";LIBUSBK_DIR=\"c:/projects/libwdi/libusbK-3.0.7.0-bin/bin\"" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
